export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_LOADING = 'SIGN_OUT_LOADING';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_LOADING = 'FETCH_TODOS_LOADING';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const MARK_TODO_DONE = 'MARK_TODO_DONE';
export const MARK_TODO_DONE_LOADING = 'MARK_TODO_DONE_LOADING';
export const MARK_TODO_DONE_SUCCESS = 'MARK_TODO_DONE_SUCCESS';
export const MARK_TODO_DONE_ERROR = 'MARK_TODO_DONE_ERROR';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_LOADING = 'UPDATE_TODO_LOADING';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const SET_NOTIFICATION_TIME = 'SET_NOTIFICATION_TIME';
export const SET_NOTIFICATION_TIME_LOADING = 'SET_NOTIFICATION_TIME_LOADING';
export const SET_NOTIFICATION_TIME_SUCCESS = 'SET_NOTIFICATION_TIME_SUCCESS';
export const SET_NOTIFICATION_TIME_ERROR = 'SET_NOTIFICATION_TIME_ERROR';

export const UPDATE_NOTIFICATION_TIME = 'UPDATE_NOTIFICATION_TIME';
export const UPDATE_NOTIFICATION_TIME_LOADING = 'UPDATE_NOTIFICATION_TIME_LOADING';
export const UPDATE_NOTIFICATION_TIME_SUCCESS = 'UPDATE_NOTIFICATION_TIME_SUCCESS';
export const UPDATE_NOTIFICATION_TIME_ERROR = 'UPDATE_NOTIFICATION_TIME_ERROR';

export const FETCH_NOTIFICATION_TIME = 'FETCH_NOTIFICATION_TIME';
export const FETCH_NOTIFICATION_TIME_LOADING = 'FETCH_NOTIFICATION_TIME_LOADING';
export const FETCH_NOTIFICATION_TIME_SUCCESS = 'FETCH_NOTIFICATION_TIME_SUCCESS';
export const FETCH_NOTIFICATION_TIME_ERROR = 'FETCH_NOTIFICATION_TIME_ERROR';

export const FETCH_PREVIOUS_DAY_TODOS = 'FETCH_PREVIOUS_DAY_TODOS';
export const FETCH_PREVIOUS_DAY_TODOS_LOADING = 'FETCH_PREVIOUS_DAY_TODOS_LOADING';
export const FETCH_PREVIOUS_DAY_TODOS_SUCCESS = 'FETCH_PREVIOUS_DAY_TODOS_SUCCESS';
export const FETCH_PREVIOUS_DAY_TODOS_ERROR = 'FETCH_PREVIOUS_DAY_TODOS_ERROR';

export const ADD_PREVIOUS_DAY_TODOS = 'ADD_PREVIOUS_DAY_TODOS';
export const NO_ADD_PREVIOUS_DAY_TODOS = 'NO_ADD_PREVIOUS_DAY_TODOS';

export const OPEN_PENDING_TODO = 'OPEN_PENDING_TODO';
export const CLOSE_PENDING_TODO = 'CLOSE_PENDING_TODO';

export const MORNING_TIME_CHANGE = 'MORNING_TIME_CHANGE';
export const EVENING_TIME_CHANGE = 'EVENING_TIME_CHANGE';

export const FETCH_LOGGED_IN_USER = 'FETCH_LOGGED_IN_USER';
export const EDIT_TODO = 'EDIT_TODO';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const DATE_CHANGE = 'DATE_CHANGE';
export const COPY_TO_CLIPBOARD = 'COPY_TO_CLIPBOARD';
export const TOAST_CLOSE = 'TOAST_CLOSE';
